"""add_documents_table

Revision ID: 37c61855a698
Revises: 
Create Date: 2026-04-21 11:02:57.958930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '37c61855a698'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('blob_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('normalized_content', sa.Text(), nullable=True),
    sa.Column('detected_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('file_category', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
